### PR TITLE
add toggle console button and exported bools for enabling print, console and toggle console button

### PR DESCRIPTION
**Pull request by JPCard**
Hi, I found your code very usefull, thanks.
I did some changes to add a button that allows opening the console on mobile builds. Besides I added some exported variables to Console.gd in order to enable/disable this new button (it is disabled by default), the ability to use the console (defaulted to true for compat) and another flag for allowing prints (defaulted to true for compat). Those last two are especially usefull for release builds where it is not desirable to use the console nor wasting resources on prints that no one will see.

### CODE REVIEW

**Comment by quentincaffeino** [comment]
Hello! Thanks, glad you liked it :)

Sadly I can't accept your pr...

> add a button that allows opening the console on mobile builds

That's a great feature but I don't think it shouldn't be a part of the console core. I believe core should be simple and allow users extend the solution. This is exactly that. Reason is that everyone wants something different, and adding all those features to one single package will make it unmaintainable pretty fast.

> flag for allowing prints

Correct me if I'm wrong but godot in release builds disables logging therefore print message doesn't do anything.

> the ability to use the console ... especially usefull for release builds

Ideally in release you shouldn't be including development tool, otherwise you are wasting resources and also possibly leaking some internal materials as dev tools not meant and almost never tested for release environments.

**Comment by JPCard** [comment]
Ok, I am with you on your first 2 arguments, but for the third one I don't know a better way to disable a tool that is probably scattered throughout code thanks to calling to Console.Write and such.
Should I check OS.is_debug_build() every time before using Console?

**Comment by quentincaffeino** [comment]
Sadly godot doesn't have any DI, so yes:
- either check OS.is_debug_build()
- or create a dummy class with same methods that do nothing and replace autoload in release build

**Comment by quentincaffeino** [comment]
Once again - thanks for your effort. Usually it is better to open an issue first to discuss such changes before putting time into implementing them :)

**Pull request closed without merging**
